"""new fields in user model

Revision ID: 40037e5bd330
Revises: 90413d63517a
Create Date: 2021-01-04 10:41:26.953263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40037e5bd330'
down_revision = '90413d63517a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
